name: Lyfesteal
version: 1.0.0
author: Dylan
main: me.dylan.LyfeSteal.Main
api-version: 1.18
commands:
  hearts:
    permission: lyfesteal.hearts
    usage: /hearts
    description: Get your current amount of hearts
    aliases: [h]
    Permissions:
      lyfesteal.hearts:
        description: "Allows the player to see their current amount of hearts"
        default: true
  hearts.help:
    permission: lyfesteal.hearts.help
    usage: /hearts help
    description: Get help on how to use the plugin
    aliases: [h.help]
    Permissions:
      lyfesteal.hearts.help:
        description: "Allows the player to see the help menu"
        default: true
  hearts.give:
    permission: lyfesteal.hearts.give
    usage: /hearts give <player> <amount>
    description: Give a player hearts
    aliases: [hg]
    Permissions:
      lyfesteal.hearts.give.others:
        default: true
        description: Give hearts to other players
        children:
          lyfesteal.hearts.give:
            description: Give hearts to other players
  hearts.set:
    permission: lyfesteal.hearts.set
    usage: /hearts set <player> <amount>
    description: Set a player's hearts
    aliases: [hs]
    Permissions:
      lyfesteal.hearts.set.others:
        description: Set other players hearts
        default: op
        children:
          lyfesteal.hearts.set:
            description: Set your hearts
  tempban:
    description: Bans a player for a set amount of time
    usage: /<command> <player> <amount> <unit>
    permission: lyfesteal.tempban
    Permissions:
      lyfesteal.tempban:
        description: Gives access to /tempban
        default: op
  tempbanexact:
    description: Bans a player for a set amount of time
    usage: /<command> <player> <amount> <unit>
    permission: lyfesteal.tempbanexact
    Permissions:
      lyfesteal.tempbanexact:
        description: Gives access to /tempbanexact
        default: op
  unban:
    description: Unbans a player
    usage: /<command> <player>
    permission: lyfesteal.unban
    Permissions:
      lyfesteal.unban:
        description: Gives access to /unban
        default: op
  check:
    description: Checks if the player is banned
    usage: /<command> <player>
    permission: lyfesteal.check
    Permissions:
      lyfesteal.check:
        description: Gives access to /check
        default: op